install_os-loganalyze fails due to missing gcc
and python-dev

unable to execute 'x86_64-linux-gnu-gcc'
Ensure it's available.

 Building wheels for collected packages: os-loganalyze, PyYAML, python-magic, MarkupSafe, simplejson, PrettyTable, msgpack-python, monotonic, netifaces, wrapt
   Running setup.py bdist_wheel for os-loganalyze
   Stored in directory: /root/.cache/pip/wheels/97/2a/a4/4ff25c6abd899c7415131a474ae40f8bdc779b7235fdb05453
   Running setup.py bdist_wheel for PyYAML
   Stored in directory: /root/.cache/pip/wheels/fa/db/f6/dee55793d344f1706dc4a5a693298f0115241d1085cc212364
   Running setup.py bdist_wheel for python-magic
   Stored in directory: /root/.cache/pip/wheels/6e/b0/a4/f919e45f80e6510c5690a3eac07396a565fa722fbe2ddc5fd6
   Running setup.py bdist_wheel for MarkupSafe
   Stored in directory: /root/.cache/pip/wheels/94/a7/79/f79a998b64c1281cb99fa9bbd33cfc9b8b5775f438218d17a7
   Running setup.py bdist_wheel for simplejson
   Stored in directory: /root/.cache/pip/wheels/4e/25/10/2ff5f7347927f4816794414d599a5383c7f8dd9a9ff729af28
   Running setup.py bdist_wheel for PrettyTable
   Stored in directory: /root/.cache/pip/wheels/41/46/ec/ec86e65e50e9f4be52547a3bedd46077e7414c53d2ed0418fd
   Running setup.py bdist_wheel for msgpack-python
   Stored in directory: /root/.cache/pip/wheels/f3/97/a5/dd6e3b680de10b689464c44bc211239d1fe54bd296ff860897
   Running setup.py bdist_wheel for monotonic
   Stored in directory: /root/.cache/pip/wheels/5e/1c/45/35891d79ba5180479226cfee4adc961ff6d766f440d8691517
   Running setup.py bdist_wheel for netifaces
   Complete output from command /usr/bin/python -c "import setuptools;__file__='/tmp/pip-build-m8Yx3M/netifaces/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpZhTYmtpip-wheel-:
   running bdist_wheel
   running build
   running build_ext
   checking for getifaddrs...not found.
   checking for getnameinfo...not found.
   checking for socket IOCTLs...not found.
   checking for optional header files...none found.
   checking whether struct sockaddr has a length field...no.
   checking which sockaddr_xxx structs are defined...none!
   checking for routing socket support...no.
   checking for sysctl(CTL_NET...) support...no.
   checking for netlink support...no.
   building 'netifaces' extension
   x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DNETIFACES_VERSION=0.10.4 -I/usr/include/python2.7 -c netifaces.c -o build/temp.linux-x86_64-2.7/netifaces.o
   unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
   error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

   ----------------------------------------
   Failed building wheel for netifaces

Change-Id: I5b15935415fb030b60bedd8199ff99696271d886